// Mock data based on your Prisma Doctor model structure
export const doctors = [
  {
    id: "d1",
    name: "Dr. Sarah Johnson",
    email: "sarah.johnson@example.com",
    profilePhoto: "https://i.ibb.co.com/1J7dm4n5/doctor.jpg",
    contactNumber: "+1 (555) 123-4567",
    address: "123 Medical Center Blvd, New York, NY",
    registrationNumber: "MED12345",
    experience: 8,
    gender: "FEMALE",
    appointmentFee: 150,
    qualification: "MD in Cardiology, Harvard Medical School",
    currentWorkingPlace: "New York Medical Center",
    designation: "Senior Cardiologist",
    averageRating: 4.8,
    specialties: ["Cardiology", "Internal Medicine"],
  },
  {
    id: "d2",
    name: "Dr. Michael Chen",
    email: "michael.chen@example.com",
    profilePhoto: "https://i.ibb.co.com/1J7dm4n5/doctor.jpg",
    contactNumber: "+1 (555) 234-5678",
    address: "456 Health Avenue, Boston, MA",
    registrationNumber: "MED23456",
    experience: 12,
    gender: "MALE",
    appointmentFee: 180,
    qualification: "MD in Neurology, Johns Hopkins University",
    currentWorkingPlace: "Boston Neurological Institute",
    designation: "Chief Neurologist",
    averageRating: 4.9,
    specialties: ["Neurology", "Neurosurgery"],
  },
  {
    id: "d3",
    name: "Dr. Emily Rodriguez",
    email: "emily.rodriguez@example.com",
    profilePhoto: "https://i.ibb.co.com/1J7dm4n5/doctor.jpg",
    contactNumber: "+1 (555) 345-6789",
    address: "789 Wellness Street, Miami, FL",
    registrationNumber: "MED34567",
    experience: 6,
    gender: "FEMALE",
    appointmentFee: 130,
    qualification: "MD in Pediatrics, Stanford University",
    currentWorkingPlace: "Miami Children's Hospital",
    designation: "Pediatric Specialist",
    averageRating: 4.7,
    specialties: ["Pediatrics", "Child Psychology"],
  },
  {
    id: "d4",
    name: "Dr. James Wilson",
    email: "james.wilson@example.com",
    profilePhoto: "https://i.ibb.co.com/1J7dm4n5/doctor.jpg",
    contactNumber: "+1 (555) 456-7890",
    address: "101 Medical Park, Chicago, IL",
    registrationNumber: "MED45678",
    experience: 15,
    gender: "MALE",
    appointmentFee: 200,
    qualification: "MD in Orthopedics, University of Chicago",
    currentWorkingPlace: "Chicago Orthopedic Center",
    designation: "Head of Orthopedic Surgery",
    averageRating: 4.9,
    specialties: ["Orthopedics", "Sports Medicine"],
  },
  {
    id: "d5",
    name: "Dr. Sophia Patel",
    email: "sophia.patel@example.com",
    profilePhoto: "https://i.ibb.co.com/1J7dm4n5/doctor.jpg",
    contactNumber: "+1 (555) 567-8901",
    address: "202 Health Boulevard, San Francisco, CA",
    registrationNumber: "MED56789",
    experience: 10,
    gender: "FEMALE",
    appointmentFee: 170,
    qualification: "MD in Dermatology, UCSF",
    currentWorkingPlace: "San Francisco Dermatology Clinic",
    designation: "Senior Dermatologist",
    averageRating: 4.8,
    specialties: ["Dermatology", "Cosmetic Dermatology"],
  },
  {
    id: "d6",
    name: "Dr. Robert Kim",
    email: "robert.kim@example.com",
    profilePhoto: "https://i.ibb.co.com/1J7dm4n5/doctor.jpg",
    contactNumber: "+1 (555) 678-9012",
    address: "303 Medical Drive, Seattle, WA",
    registrationNumber: "MED67890",
    experience: 9,
    gender: "MALE",
    appointmentFee: 160,
    qualification: "MD in Ophthalmology, University of Washington",
    currentWorkingPlace: "Seattle Eye Clinic",
    designation: "Ophthalmologist",
    averageRating: 4.6,
    specialties: ["Ophthalmology", "LASIK Surgery"],
  },
];

export const specialties = [
  {
    id: "s1",
    title: "Cardiology",
    icon: "Heart",
    description: "Diagnosis and treatment of heart disorders",
  },
  {
    id: "s2",
    title: "Neurology",
    icon: "Brain",
    description: "Diagnosis and treatment of nervous system disorders",
  },
  {
    id: "s3",
    title: "Pediatrics",
    icon: "Baby",
    description: "Medical care for infants, children, and adolescents",
  },
  {
    id: "s4",
    title: "Orthopedics",
    icon: "Bone",
    description: "Treatment of musculoskeletal system",
  },
  {
    id: "s5",
    title: "Dermatology",
    icon: "Scan",
    description: "Diagnosis and treatment of skin disorders",
  },
  {
    id: "s6",
    title: "Ophthalmology",
    icon: "Eye",
    description: "Diagnosis and treatment of eye disorders",
  },
  {
    id: "s7",
    title: "Dentistry",
    icon: "Smile",
    description: "Diagnosis and treatment of dental issues",
  },
  {
    id: "s8",
    title: "Psychiatry",
    icon: "Brain",
    description: "Diagnosis and treatment of mental disorders",
  },
];

export const testimonials = [
  {
    id: "t1",
    name: "Jennifer Adams",
    image: "/placeholder.svg?height=100&width=100",
    role: "Patient",
    comment:
      "The doctors here are incredibly knowledgeable and caring. I've never felt more comfortable discussing my health concerns.",
    rating: 5,
  },
  {
    id: "t2",
    name: "Mark Thompson",
    image: "/placeholder.svg?height=100&width=100",
    role: "Patient",
    comment:
      "The online appointment system is so convenient, and the doctors are always punctual. Great healthcare experience!",
    rating: 4,
  },
  {
    id: "t3",
    name: "Sophia Chen",
    image: "/placeholder.svg?height=100&width=100",
    role: "Patient",
    comment:
      "I appreciate how thorough the doctors are with their examinations and explanations. They take the time to answer all my questions.",
    rating: 5,
  },
];

export const stats = [
  { value: "200+", label: "Expert Doctors" },
  { value: "30+", label: "Medical Specialties" },
  { value: "15K+", label: "Happy Patients" },
  { value: "10+", label: "Years of Experience" },
];

export const services = [
  {
    id: "sv1",
    title: "Online Consultation",
    description:
      "Connect with doctors from the comfort of your home via video calls",
    icon: "Video",
  },
  {
    id: "sv2",
    title: "In-Person Visits",
    description: "Schedule face-to-face appointments with our specialists",
    icon: "Users",
  },
  {
    id: "sv3",
    title: "Emergency Care",
    description: "24/7 emergency medical services for urgent health concerns",
    icon: "Siren",
  },
  {
    id: "sv4",
    title: "Lab Tests",
    description: "Comprehensive diagnostic tests with quick results",
    icon: "FlaskConical",
  },
];

export const schedules = [
  {
    doctorId: "d1",
    slots: [
      {
        id: "slot1",
        date: "2023-05-15",
        startTime: "09:00 AM",
        endTime: "09:30 AM",
        isBooked: false,
      },
      {
        id: "slot2",
        date: "2023-05-15",
        startTime: "10:00 AM",
        endTime: "10:30 AM",
        isBooked: true,
      },
      {
        id: "slot3",
        date: "2023-05-16",
        startTime: "11:00 AM",
        endTime: "11:30 AM",
        isBooked: false,
      },
    ],
  },
  {
    doctorId: "d2",
    slots: [
      {
        id: "slot4",
        date: "2023-05-15",
        startTime: "02:00 PM",
        endTime: "02:30 PM",
        isBooked: false,
      },
      {
        id: "slot5",
        date: "2023-05-16",
        startTime: "03:00 PM",
        endTime: "03:30 PM",
        isBooked: false,
      },
      {
        id: "slot6",
        date: "2023-05-17",
        startTime: "04:00 PM",
        endTime: "04:30 PM",
        isBooked: true,
      },
    ],
  },
];
